[package]
name = "bevy_sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.10.1", default-features = false, features = ["bevy_scene"] }
bevy_renet = "0.0.8"
bincode = "1.3.3"
serde = { version = "1.0.160", features = ["derive"] }

[dev-dependencies]
portpicker = "0.1.1"
