[package]
name = "bevy_sync"
version = "0.12.2"
edition = "2021"
authors = ["Raffaele Ragni <raffaele.ragni@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Plugin for synchronizing entities and components between server and its clients."
homepage = "https://github.com/raffaeleragni/bevy_sync"
repository = "https://github.com/raffaeleragni/bevy_sync"
documentation = "https://github.com/raffaeleragni/bevy_sync/blob/master/README.md"
readme = "README.md"
keywords = ["bevy", "netcode", "synchronization"]
categories = ["game-development", "network-programming"]
include = ["/src", "/LICENSE-MIT", "/LICENSE-APACHE"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12"
bevy_renet = "0.0.10" 
bincode = "1.3.3"
serde = { version = "1.0.160", features = ["derive"] }

[dev-dependencies]
portpicker = "0.1.1"
serial_test = "2.0.0"
bevy_editor_pls = "0.6"
uuid = "1.5.0"
